services:
  postgres:
    image: postgres:17
    container_name: nivora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: nivora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"